apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cpd-tobo-dev
  name: cpd-tobo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cpd-tobo-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cpd-tobo-dev
    spec:
      restartPolicy: Always
      serviceAccountName: ""
      containers:
      - image: "{{ .Values.docker_registry }}/bergauer/services/cpd/cpd-tobo-dev:{{ .Chart.AppVersion }}"
        imagePullPolicy: ""
        name: cpd-tobo-dev
        env:
            - name:  "SERVICENAME"
              value: "{{ .Values.env.SERVICENAME }}"

status: {}

